name: firework_distance
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # 状態管理のためのフレームワーク (Riverpod)
  freezed_annotation: ^3.1.0 # Freezed（イミュータブルなクラスを生成するコードジェネレーター）のアノテーションを提供
  hooks_riverpod: ^2.6.1 # RiverpodでReact Hooksライクな機能を使えるようにするパッケージ
  permission_handler: ^12.0.1 # カメラやマイクなどのデバイス権限を扱うためのプラグイン
  shared_preferences: ^2.2.3 # テーマ設定を永続化するためのパッケージ

dev_dependencies:
  build_runner: ^2.5.4 # コード生成を実行するためのコマンドラインツール
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0 # イミュータブルなデータクラスやユニオン型を簡単に作成するためのコードジェネレーター
  riverpod_generator: ^2.6.5 # RiverpodのProviderを自動生成するためのコードジェネレーター
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
