name: Flutter setup
description: Flutter setup
runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2.12.0
      with:
        flutter-version: '3.32.7'
        channel: 'stable'
        cache: true
    - run: flutter doctor -v
      shell: bash
    - run: flutter pub get
      shell: bash
