name: Tests
# Flutterのtestを実行

on:
  pull_request:
    branches:
      - main
      - develop
      - sprint/**
      - feature/**
      - hotfix/**
  release:
    types:
      - published

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/flutter_setup

      - name: Run linter
        run: flutter analyze

  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/flutter_setup

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Run tests
        run: |
          flutter test --coverage
          lcov --remove coverage/lcov.info -o ./coverage/lcov_with_exclusion.info  '**.graphql.dart' '**firebase_options_*.dart' '**/theme/*'

      - name: Upload code coverage to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage/lcov_with_exclusion.info

  coverage_report:
    name: Generate coverage report
    needs: unit-test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download code coverage from GitHub
        uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: coverage

      - name: Install lcov
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4.1.22
        with:
          coverage-files: coverage/lcov_with_exclusion.info
          # 今後テストを充実させていったら閾値設定をする
          #minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
